version: "2.1"

services:
  eurekaregistry:
    build:
      context: ../eurekaregistry
      dockerfile: eurekaregistry.Dockerfile
    image: eurekaregistry
    container_name: eurekaregistry
    environment:
      - SPRING_PROFILES_ACTIVE=peer1
      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    expose:
      - 8761
    ports:
      - "8761:8761"
    networks:
      - progetto-labProg

  seekers:
    build:
      context: ../seekers
      dockerfile: seekers.Dockerfile
    image: seekers
    container_name: seekers
    expose:
      - 8300
    networks:
      - progetto-labProg
    depends_on:
      seekersdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
    ports:
      - "8300:8300"
    restart: on-failure
    mem_limit: 500M

  advisor:
    build:
      context: ../advisor
      dockerfile: advisor.Dockerfile
    image: advisor
    container_name: advisor
    expose:
      - 8700
    networks:
      - progetto-labProg
    depends_on:
      eurekaregistry:
        condition:
          service_started
      jobsdb:
        condition:
          service_healthy
    restart: on-failure
    mem_limit: 500M

  applications:
    build:
      context: ../applications
      dockerfile: applications.Dockerfile
    image: applications
    container_name: applications
    expose:
      - 8600
    networks:
      - progetto-labProg
    depends_on:
      applicationsdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
    restart: on-failure
    mem_limit: 500M

  applicationsdb:
    image: postgres
    container_name: applicationsdb
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    volumes:
      - applicationsdbdata:/var/lib/postgresql/data
    networks:
      - progetto-labProg
    healthcheck:
      test: "exit 0"
    mem_limit: 200M

  jobsdb:
    image: postgres
    container_name: jobsdb
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    volumes:
      - jobsdbdata:/var/lib/postgresql/data
    networks:
      - progetto-labProg
    healthcheck:
      test: "exit 0"
    mem_limit: 200M

  jobcenters:
    build:
      context: ../jobcenters
      dockerfile: jobcenters.Dockerfile
    image: jobcenters
    container_name: jobcenters
    expose:
      - 8200
    networks:
      - progetto-labProg
    depends_on:
      centersdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
    restart: on-failure
    mem_limit: 500M

  jobsdb:
    image: postgres
    container_name: jobsdb
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    volumes:
      - jobsdbdata:/var/lib/postgresql/data
    networks:
      - progetto-labProg
    healthcheck:
      test: "exit 0"
    mem_limit: 200M

  jobs:
    build:
      context: ../jobs
      dockerfile: jobs.Dockerfile
    image: jobs
    container_name: jobs
    expose:
      - 8400
    networks:
      - progetto-labProg
    depends_on:
      jobsdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
    restart: on-failure
    mem_limit: 500M

  search:
    build:
      context: ../search
      dockerfile: search.Dockerfile
    image: search
    container_name: search
    expose:
      - 8500
    networks:
      - progetto-labProg
    depends_on:
      jobsdb:
        condition:
          service_healthy
      eurekaregistry:
        condition:
          service_started
    restart: on-failure
    mem_limit: 500M

  seekersdb:
    image: postgres
    container_name: seekersdb
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    volumes:
      - seekersdbdata:/var/lib/postgresql/data
    networks:
      - progetto-labProg
    healthcheck:
      test: "exit 0"
    mem_limit: 200M

  centersdb:
    image: postgres
    container_name: centersdb
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    volumes:
      - centersdbdata:/var/lib/postgresql/data
    networks:
      - progetto-labProg
    healthcheck:
      test: "exit 0"
    mem_limit: 200M

  notification:
    build:
      context: ../notification
      dockerfile: notification.Dockerfile
    image: notification
    container_name: notification
    expose:
      - 8900
      - 8888
    networks:
      - progetto-labProg
    depends_on:
      eurekaregistry:
        condition:
          service_started
    restart: on-failure
    mem_limit: 500M

networks:
  progetto-labProg:
    driver: bridge

volumes:
  jobsdbdata:
  seekersdbdata:
  centersdbdata:
  jobsdbdata:
  applicationsdbdata:
